# Generated by Django 2.2.5 on 2019-09-03 06:22

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=30, verbose_name='标题')),
                ('a_content', DjangoUeditor.models.UEditorField(blank=True, default='test', verbose_name='内容')),
                ('a_uploadTime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('a_readnum', models.IntegerField(default=0, editable=False, verbose_name='阅读数')),
                ('a_likenum', models.IntegerField(default=0, editable=False, verbose_name='赞赏数')),
                ('a_pic', models.ImageField(upload_to='index/article_img', verbose_name='图片')),
                ('a_isdelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20, verbose_name='标签名')),
                ('Fisdelete', models.BooleanField(default=False, verbose_name='已删除')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('Ucontent', models.CharField(max_length=100, verbose_name='个人简介')),
                ('Uisdelete', models.BooleanField(default=False, verbose_name='已删除')),
                ('Uimg', models.ImageField(upload_to='index/user_img', verbose_name='头像')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filter_Tags_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Filter')),
                ('Tags_Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuser', models.CharField(max_length=30)),
                ('Ccontent', models.CharField(max_length=200)),
                ('Cisdelete', models.BooleanField(default=False)),
                ('Comments_Article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
    ]
