# Generated by Django 2.2.5 on 2019-09-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190903_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_pic', models.ImageField(upload_to='blog/article_img', verbose_name='图片')),
                ('h_title', models.CharField(max_length=20, verbose_name='主题')),
                ('h_content', models.CharField(max_length=20, verbose_name='简介')),
            ],
        ),
    ]
