# Generated by Django 2.2.5 on 2019-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tags_header_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='header_pic',
        ),
        migrations.AddField(
            model_name='filter',
            name='header_pic',
            field=models.ImageField(default='', upload_to='blog/tags_pic', verbose_name='图片'),
        ),
    ]
