# Generated by Django 2.2.5 on 2019-12-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190908_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('is_lock', models.CharField(default='2', max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='Cdate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
